---
name: "CustomLogo"
guid: "eb5d7894-8eef-4b36-aa6f-5d124e828ce1"
imageUrl: "https://raw.githubusercontent.com/ImLacy/Jellyfin-CustomLogo/refs/heads/main/logo.png"
version: "1.0.0.3"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Add the abiliy to replace the Jellyfin logo"
category: "General"
owner: "Lacy"
artifacts:
- "CustomLogo.dll"
changelog: >
  changelog
